export const sampleCars = [
  {
    title: "Lamborghini Urus Mansory Edition",
    brand: "Lamborghini",
    model: "Urus Mansory",
    year: 2020,
    category: "SUV",
    dailyRate: 3000,
    monthlyRate: 50000,
    location: "Sheikh Zayed Road",
    imageUrl:
      "https://static.oneclickdrive.com/uploads/cars/Nissan-Patrol-SE-Platinum-City-V6-2026_39647_32781115108-11_small.jpg",
    isPremium: true,
    availableForRent: true,
    status: "approved",
  },
  {
    title: "BMW X5 M Competition",
    brand: "BMW",
    model: "X5 M Competition",
    year: 2023,
    category: "SUV",
    dailyRate: 1200,
    monthlyRate: 25000,
    location: "Dubai Marina",
    imageUrl:
      "https://static.oneclickdrive.com/uploads/cars/Nissan-Patrol-SE-Platinum-City-V6-2026_39647_32781115108-11_small.jpg",
    isPremium: true,
    availableForRent: true,
    status: "pending",
  },
  {
    title: "Mercedes-Benz G63 AMG",
    brand: "Mercedes-Benz",
    model: "G63 AMG",
    year: 2022,
    category: "SUV",
    dailyRate: 2500,
    monthlyRate: 45000,
    location: "Downtown Dubai",
    imageUrl:
      "https://static.oneclickdrive.com/uploads/cars/Nissan-Patrol-SE-Platinum-City-V6-2026_39647_32781115108-11_small.jpg",
    isPremium: true,
    availableForRent: true,
    status: "approved",
  },
  {
    title: "Toyota Camry Hybrid",
    brand: "Toyota",
    model: "Camry Hybrid",
    year: 2023,
    category: "Sedan",
    dailyRate: 180,
    monthlyRate: 4500,
    location: "Business Bay",
    imageUrl:
      "https://static.oneclickdrive.com/uploads/cars/Nissan-Patrol-SE-Platinum-City-V6-2026_39647_32781115108-11_small.jpg",
    isPremium: false,
    availableForRent: true,
    status: "approved",
  },
  {
    title: "Porsche 911 Turbo S",
    brand: "Porsche",
    model: "911 Turbo S",
    year: 2023,
    category: "Coupe",
    dailyRate: 2800,
    monthlyRate: 55000,
    location: "Palm Jumeirah",
    imageUrl:
      "https://static.oneclickdrive.com/uploads/cars/Nissan-Patrol-SE-Platinum-City-V6-2026_39647_32781115108-11_small.jpg",
    isPremium: true,
    availableForRent: true,
    status: "pending",
  },
  {
    title: "Honda Civic",
    brand: "Honda",
    model: "Civic",
    year: 2022,
    category: "Sedan",
    dailyRate: 120,
    monthlyRate: 2800,
    location: "Deira",
    imageUrl:
      "https://static.oneclickdrive.com/uploads/cars/Nissan-Patrol-SE-Platinum-City-V6-2026_39647_32781115108-11_small.jpg",
    isPremium: false,
    availableForRent: true,
    status: "rejected",
  },
];
